### ISSUE TITLE
set-version with ivy build system causes failures for OSGi-module artifacts

### ISSUE THREAD

**Issue by jsuereth** [lightbend-labs/dbuild#109]
If:
- You use ivy build system
- You are resolving a `<packaging>bundle</packaging>` OSGi artifact from maven
- You have a `set-version` clause.

It appears that the republished artifact drops the notion of "bundle" for "jar" and see resolving the new version breaks.

**Comment by SethTisue** [comment]
hasn't bitten the community build 🤷
