### ISSUE TITLE
Support per-project JVM selection

### ISSUE THREAD

**Issue by retronym** [lightbend-labs/dbuild#139]
I've found the only reliable way to ensure SBT uses Java 8 on the compilation and execution classpath is to start SBT with Java 8 on the path. (Last time I checked, the `javaHome` setting only changes the compilation classpath).

As we move to a community build that used Java 8, it is likely we'll encounter some constituent projects that still require an older Java version to build them. I found this recently with a project that was built with SBT 0.12.5-dbuild; that SBT version brings in Scala 2.9.3 which is incompatible with Java 8 bytecode.

I suggest we allow JAVA_HOME to be overriden on a per-project basis. Dbuild could then prepend this to the PATH when forking the child JVM to run that projects build. While we are at it, we could add support for custom JVM command line options.

In a Jenkins environment, this feature would work well with the [Tool Environment Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Tool+Environment+Plugin) which exposes all the configured JDKs in the environment of the job, rather than just the one selected in the job configuration.

**Comment by SethTisue** [comment]
not really an issue for the Scala community build anymore. we have separate 2.11x (JDK6) and 2.11.x-jdk8 branches. if a project doesn't support Java 6 or 7 anymore, we only add it to the latter. (these days we aren't adding much to either one actually, the action is on 2.12.)

**Comment by SethTisue** [comment]
this may become an issue again (as brought up by @retronym the other day) because of Java 9

**Comment by SethTisue** [comment]
we're doing fine with separate 8, 11, and 17 builds with differing expected-to-fail lists
