### ISSUE TITLE
Report all missing Scala dependencies

### ISSUE THREAD

**Issue by gkossakowski** [lightbend-labs/dbuild#140]
At the moment dbuild will report just one missing Scala dependency that is not already added to the config file. It means one need to rerun dbuild for each missing dependency. Given that each dbuild invocation is quite slow, the experience of somebody adding a new project to dbuild configuration is not that great.

Possible workaround: fire up `consoleProject` and list all Scala dependencies. My sbt-foo is not good enough to offer a code snippet to run, though.

**Comment by SethTisue** [comment]
yeah, this is a pain point

**Comment by SethTisue** [comment]
not so painful anymore now that the 2.12 build is largely frozen and the 2.13 build was restructured
