### ISSUE TITLE
Dbuild insits building tests when there are none

### ISSUE THREAD

**Issue by gkossakowski** [lightbend-labs/dbuild#161]
Quoting @sjrd:

> These weird things are "normal". Well, it's dbuild's fault: it insists on compiling the Test config of every project in the dependency chain. But library doesn't have any source in its Test config (the tests actually being in the testSuite project). These things appear as [error] mostly because scalac just prints the usage on stderr if it is given 0 sources to compile. But if it doesn't fail the build, it means scalac takes it as a warning and still reports success, which is what we want.
> (scala/community-builds#65)

I don't know why this happens but here's the full log: https://jenkins-dbuild.typesafe.com:8499/job/Community-2.11.x-manual/142/consoleFull

**Comment by SethTisue** [comment]
seems like a limitation we can live with
