### ISSUE TITLE
can I skip re-fetching of the repos?

### ISSUE THREAD

**Issue by SethTisue** [lightbend-labs/dbuild#210]
now that the community build has over 160 projects in it, when I'm testing changes locally, doing `git fetch` on all the repos to see whether each project's dependencies need to be re-extracted takes a while.

this is by far the biggest factor causing a slow feedback loop on typical changes.

is there a way to tell dbuild "I don't care about any remote changes right now, just use whatever you already have locally"?

**Comment by SethTisue** [comment]
@cunei we discussed this in person in Montreal last week and I think I was able to convince you that a "don't go to GitHub, just use what you have" flag would be useful to me in community build work. and this is the reminder you asked for :-)

**Comment by SethTisue** [comment]
I feel like we discussed a few other related possibilities, but I'm forgetting now what they were.

I think one of them might have been, can we not only skip talking to GitHub, but also skip recomputing the inter-project dependencies entirely and just jump right into building? is there enough cached information to do that?

**Comment by cunei** [comment]
@SethTisue You may be interested in the branch https://github.com/lightbend/dbuild/commits/wip-INPROGRESS-disableUpdates, which should be now complete. :blush: It is published as version `0.9.17-toni4`,t you can try it out now.
It adds:
- an option '-s', aka '--skip-git-updates`, to bypass remote git updates
- huge improvements to git fetch operations, which by default now retrieve only the minimum amount of information for the specific branch/tag/PR requested
- an optional `?shallow=false` uri query, to request a full clone when needed (see docs)

The speed improvements are substantial; when remote updates are disabled, the full extraction of the community build takes about a minute and a half.

**Comment by cunei** [comment]
A matching update to the community build is at: https://github.com/cunei/community-builds/commits/wip-testing-toni4

**Comment by cunei** [comment]
@SethTisue I made further improvements and optimizations. Now, re-extracting the 188 projects of the community build, with all cached and updates disables, takes just 8 seconds:
```
$ ./run.sh -lds 2>&1 | ts '[%T]'
[...]
[10:31:04] [acyclic] --== Extracting dependencies for acyclic ==--
[...]
[10:31:12] [zinc] --== End Extracting dependencies for zinc ==--
[10:31:12] [info] ---== Dependency Information ===---
[...]
```
You can test it by using dbuild version 0.9.17-toni20.
The matching changes to the community buld (only tested up to the end of extraction) are at https://github.com/cunei/community-builds/commits/wip-testing-toni20

**Comment by ashawley** [comment]
> an option '-s', aka '--skip-git-updates`, to bypass remote git updates

Why not wrap these various behaviors of Git and sbt skipping update in to something called `--offline` mode, as it is called in Maven and sbt?  That way, you can run dbuild on plane rides.

Also, why not use `--depth=1` on the initial git clone (maybe by default).  This would be a lot easier for first time users, reduce the disk storage requirements, and also avoid abusing GitHub.

**Comment by SethTisue** [comment]
I'll have to look at this in January

**Comment by SethTisue** [comment]
the `narrow.sc` script has pretty much removed this pain; you can use it so only the repos you care about at the moment are fetched or extracted
