### ISSUE TITLE
Ivy build system should be able to share local cache with sbt

### ISSUE THREAD

**Issue by jsuereth** [lightbend-labs/dbuild#45]
This means we should be using the same mechanisms as sbt to prevent "which repository this came from" information from corrupting the cache.  However, we should be able to share resolution of ivy artifacts, so we don't take a long time to resolve things, but can share results between builds for "stable" artifacts.  (thinks  published to maven/ivy).

**Comment by SethTisue** [comment]
hasn't bitten the community build 🤷
