### ISSUE TITLE
sbt-republish may fail in 0.7.0

### ISSUE THREAD

**Issue by cunei** [lightbend-labs/dbuild#81]
There seems to be a mismatch concerning compiler-interface, in certain cases. For instance, in one test case the sbt jar published after the compilation of sbt is:
`org.scala-sbt/compiler-interface_2.11.0-dbuildx1317a1280278e3f43e6d797a110a8f1a71fe410e/0.13.1-dbuildx7efb24a03fb92a1fec9a58adf4d9f9ad17ff018e/jars/compiler-interface-src_2.11.0-dbuildx1317a1280278e3f43e6d797a110a8f1a71fe410e.jar`
but the file that sbt republish looks for is:
`org.scala-sbt/compiler-interface_2.11.0-dbuildx1317a1280278e3f43e6d797a110a8f1a71fe410e/0.13.1-dbuildx7efb24a03fb92a1fec9a58adf4d9f9ad17ff018e/jars/compiler-interface-src.jar`
That has to be a mismatch arising from one of the refactorings that intervened between 0.6.5 and 0.7.0; I'm investigating now.

**Comment by SethTisue** [comment]
hasn't bitten the community build 🤷
